### ISSUE TITLE
Zion replies with 500 when DB is reset during execution

### ISSUE THREAD

**Issue by ivanzy** [vaimee/zion#10]
This is a minor issue and probably represents a corner case that very few users will experience.  Nevertheless, if the DB gets reset (totally erased) when Zion is executing, Zion tries to make queries in tables that do not exist, throwing a 500 error.  I experienced these problems when performing some tests in Zion where I needed to reset the DB manually.  The screenshot below illustrates the issue. 

![Screenshot from 2022-07-29 13-03-39](https://user-images.githubusercontent.com/12630498/181781805-c693b422-1eab-4649-9ff9-f93f492b21b0.png)

**Comment by relu91** [comment]
Not sure how to solve this, do yo expect that zion would automatically re-populate the database?

**Comment by relu91** [comment]
We concluded that is the right behavior, does not makes sense to re-generate the schema.
