### ISSUE TITLE
Incorrect /.well-known URL

### ISSUE THREAD

**Issue by benfrancis** [vaimee/zion#6]
Zion hosts the Thing Description of the directory at `/well-known/wot`. My understanding of the [specification](https://w3c.github.io/wot-discovery/#introduction-well-known) is that it should be  `/.well-known/wot`, which currently returns a 404.

I also noticed that link to the Thing Description in the Zion HTML UI server at `/` links to `/well-known/wot-thing-description` which returns a 404.

P.S. Congrats on the release! Great to see the WoT Discovery specification in action.

**Comment by relu91** [comment]
> P.S. Congrats on the release! Great to see the WoT Discovery specification in action.

Thank you again!! we are doing our best 💪🏻 . 

> Zion hosts the Thing Description of the directory at /well-known/wot. My understanding of the [specification](https://w3c.github.io/wot-discovery/#introduction-well-known) is that it should be /.well-known/wot, which currently returns a 404.

This is of course a silly typo, fixing it 👍🏻 . 

> I also noticed that link to the Thing Description in the Zion HTML UI server at / links to /well-known/wot-thing-description which returns a 404.

Ah, that was tricky, it is some left over when we didn't have the landing page. It is probably also related to #7.

**Comment by relu91** [comment]
> I also noticed that link to the Thing Description in the Zion HTML UI server at / links to /well-known/wot-thing-description which returns a 404.

Already fixed in e7b2988f34a9245a2b88655649ec86484f380d0f.
